pkg = "assets"
dest = "./pkg/assets/"
fmt = false

clean = true
output = "ab0x.go"
unexporTed = false
spread = true
debug = false

[[custom]]
files = ["./ui/dist/"]
base = "./ui/dist/"
exclude = [".DS_Store"]
