kind: pipeline
name: default

workspace:
  base: /go
  path: appsrc/

steps:
  - name: fetch
    image: docker:git
    when:
      event:
        - tag
    commands:
        - git fetch --tags

  - name: ui
    image: node
    when:
      event:
        - tag
    commands:
      - cd ui
      - yarn install
      - yarn build

  - name: build
    image: xbapps/goreleaser-xcgo:latest
    environment:
      GOPROXY: "https://proxy.golang.org/"
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    when:
      event:
        - tag
    commands:
      - goreleaser --skip-validate --rm-dist

  - name: docker
    image: plugins/docker:18.09
    when:
      event:
        - tag
    settings:
      username:
        from_secret: DOCKER_LOGIN
      password:
        from_secret: DOCKER_PASSWORD
      repo: xbapps/xbvr
      auto_tag: true
      tags: latest
      build_args: DRONE_TAG=${DRONE_TAG}
      dockerfile: .drone.dockerfile
