before:
  hooks:
    - go mod download
    - go get github.com/UnnoTed/fileb0x
    - go generate ./...

builds:
- id: xbvr-windows
  binary: xbvr
  main: pkg/tray/main.go
  flags:
    - -tags=json1
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -H windowsgui
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  goos:
    - windows
  goarch:
    - amd64

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  disable: false
  github:
    owner: xbapps
    name: xbvr
