name: Clear Workflow History

on:
  workflow_dispatch: # Чтобы запускать вручную из вкладки Actions
  schedule:
    - cron: '0 0 * * 0' # Каждое воскресенье в полночь

permissions:
  actions: write

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0 # 0 — удалить абсолютно всё
          keep_minimum_runs: 2
